[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environment]
NODE_ENV = "production"
PORT = 8080
HOST = "0.0.0.0"